version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
    volumes:
      - db_data:/var/lib/mysql
      - ./task_db.sql:/docker-entrypoint-initdb.d/task_db.sql

  web:
    build: 
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
